# LLM Sports Trainer 開発専用docker-compose.yml
#
# 概要: 開発環境専用のDocker Compose設定
# 主な仕様: ホットリロード、デバッグ、開発ツールを含む
# 制限事項: 本番環境では使用しない

version: '3.8'

services:
  # 開発用メインアプリケーション
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: llm_sports_trainer_dev
    ports:
      - "8501:8501"  # Streamlit
      - "8888:8888"  # Jupyter
      - "5678:5678"  # デバッグポート
      - "3000:3000"  # 開発サーバー
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 forwarding
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DEBUG=1
      - ENVIRONMENT=development
    env_file:
      - .env
    working_dir: /app
    command: ["python", "main.py", "--help"]
    restart: unless-stopped
    networks:
      - llm_sports_dev_network
    profiles:
      - development

  # 開発用Jupyter環境
  dev-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: llm_sports_trainer_dev_jupyter
    ports:
      - "8889:8888"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
      - jupyter_data:/home/jovyan/.jupyter
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    working_dir: /app
    command: [
      "jupyter", "lab",
      "--ip=0.0.0.0",
      "--port=8888",
      "--no-browser",
      "--allow-root",
      "--NotebookApp.token=''",
      "--NotebookApp.password=''",
      "--NotebookApp.allow_origin='*'"
    ]
    restart: unless-stopped
    networks:
      - llm_sports_dev_network
    profiles:
      - development

  # 開発用デバッグ環境
  dev-debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: llm_sports_trainer_dev_debug
    ports:
      - "5679:5678"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    working_dir: /app
    command: [
      "python", "-m", "debugpy",
      "--listen", "0.0.0.0:5678",
      "--wait-for-client",
      "main.py", "--help"
    ]
    restart: unless-stopped
    networks:
      - llm_sports_dev_network
    profiles:
      - development

  # 開発用Streamlit環境
  dev-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: llm_sports_trainer_dev_streamlit
    ports:
      - "8502:8501"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    working_dir: /app
    command: [
      "streamlit", "run", "main.py",
      "--server.port=8501",
      "--server.address=0.0.0.0",
      "--server.headless=true",
      "--server.enableCORS=false",
      "--server.enableXsrfProtection=false"
    ]
    restart: unless-stopped
    networks:
      - llm_sports_dev_network
    profiles:
      - development

  # 開発用テスト環境
  dev-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: llm_sports_trainer_dev_test
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TESTING=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    working_dir: /app
    command: ["python", "-m", "pytest", "-v", "--cov=.", "--cov-report=html"]
    networks:
      - llm_sports_dev_network
    profiles:
      - development

# ネットワーク設定
networks:
  llm_sports_dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ボリューム設定
volumes:
  jupyter_data:
    driver: local
  data:
    driver: local
  logs:
    driver: local
  models:
    driver: local 
